version: "3.3"
services:
  sender-rmq:
      build: ./Sender
      ports:
        - "80:3000"
      depends_on:
        - rabbitmq

  receiver-rmq:
      build: ./Receiver
      depends_on:
        - rabbitmq
        - server-go-rmq
        - mongo-server

  mongo-server:
      build: ./MongoServer
      depends_on:
        - rabbitmq
        - server-go-rmq
        - mongo-server
  
  rabbitmq:
      image : rabbitmq:3-management
      ports: 
          - "5672:5672"
          - "15672:15672"