version: "3.3"
services:
  rabbitmq:
      image : rabbitmq:3-management
      ports: 
          - "5672:5672"
          - "15672:15672"

  sender-rmq:
      build: ./Sender
      ports:
        - "80:3000"
      depends_on:
        - rabbitmq

  receiver-rmq:
      build: ./Receiver
      restart: on-failure
      depends_on:
        - rabbitmq

  mongo-server:
      build: ./MongoServer